version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php81
    depends_on:
      - db
    volumes:
      #- ./naujas:/var/www/html/
      - ./naujas:/var/www/
    ports:
      - 80:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoplius
    ports:
      - 6033:3306